### ISSUE TITLE
Confusing/Incorrect Documentation

### ISSUE THREAD

**Issue by myztillx** [custom-components/sensor.plex_recently_added#67]
**Describe the Bug**
Why is all the README documentation about Upcoming Media Card and not plex recently added?

**The Error**
N/A

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md)**
N/A

**What data does the sensor display if any?**
N/A

**What displays when visiting the API URL from the troubleshooting guide?**
N/A

**Does the default Home Assistant Plex component work for you?**
N/A

**Home Assistant Version**
N/A

**Additional Context**
N/A

**Comment by mkanet** [comment]
Hi @myztillx.  The README.md for `sensor.plex_recently_added` hasn't changed:
https://github.com/custom-components/sensor.plex_recently_added/blob/master/README.md

However, the `Upcoming Media Card`'s README.md  _has_ changed; since there are new features for it that were just released:
https://github.com/custom-components/sensor.plex_recently_added/blob/master/README.md

The troubleshooting doc you referenced is the troubleshooting guide for Upcoming Media Card:
https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md

Let me know if there are any specific changes you would like to see in either README.md above or any other documentation changes.

**Comment by myztillx** [comment]
Following your first link (https://github.com/custom-components/sensor.plex_recently_added/blob/master/README.md) the title of the readme is Upcoming Media Card. It seems it might have been changed in error when updating Upcoming Media Cards readme.

The troubleshooting guide I linked was just part of the issue template when I opened this issue.

**Comment by mkanet** [comment]
Thanks for catching that!  I think I might have inadvertently changed the title by accident.  I just fixed it:

https://github.com/custom-components/sensor.plex_recently_added/blob/master/README.md

**Comment by myztillx** [comment]
>It seems that https://github.com/custom-components/sensor.plex_recently_added/commit/be934a8f52eaa7cd64aa977f581b4c6be6ce8eac was the commit that caused the errors and changed the Plex readme to the Upcoming Media readme. Not just the title is different; the entire readme is wrong.

Yes, that's where I made my mistake.  I attempted to correct my mistake right away in a subsequent update; however, I had missed changing the title back.
