### ISSUE TITLE
[Feature Request] Display 'Recently Added' from specific libraries only

### ISSUE THREAD

**Issue by mayorgergich** [custom-components/sensor.plex_recently_added#74]
**Is your feature request related to a problem? Please describe.**
I have several Movie and Show libraries and don't always want to display the most recent items from specific libraries.

**Describe the solution you'd like**
Config option to display content only from specific libraries

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mkanet** [comment]
Hi there, it sounds like your trying to install the really old version of this integration from a couple of years back.  Since the new version of this integration isn't yet available on HACS, you will have to manually add the repo URL to Home Assistant (HACS) like this:

1. Navigate to HACS on Home Assistant
2. Click on the Integrations section of HACS
3. Click on the 3 dots (on the top/right of the screen) and select `Custom Repositories`
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/c4e191ab-679e-4526-b907-6e138db64318)
4. Next, copy and paste `https://github.com/custom-components/sensor.plex_recently_added` into the Repository failed and also select "Integration" for the Category, like this:
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/54ac65f5-8597-4e54-bcab-bc51eece7478)
 into the Repository field and select Integration like this:
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/ce940fa3-a2c8-4da8-96ce-b80ba4386cf2)
5. Click on **ADD**

After you do that you should see the official Plex Recently Added Integration.  The current version is: **0.4.1**,  If the version says that, then that is the correct repo, otherwise you are adding the really old version version.

Please note after you do this, you will see a warning under HACS like below.  You can click on SHOW, then click IGNORE.  **This will warning should go away as soon as the HACS moderators approve/merge my PR to HACS.**

**Comment by mkanet** [comment]
Thank you for this feature suggestion!  You will most likely see this feature available in the next version.

**Comment by mayorgergich** [comment]
Great -- thank you.

**Comment by mkanet** [comment]
Closing this issue since this feature was recently added.  In fact, it was one of the most popular feature requests.
