### ISSUE TITLE
[Feature Request] Music Library support 

### ISSUE THREAD

**Issue by moonbit5** [custom-components/sensor.plex_recently_added#79]
Hi I noticed this repo has come back to life and want to ask if music library support is on the roadmap? Thanks!

**Comment by mkanet** [comment]
@mousemat86  Yes, I didn't want [UMC](https://github.com/custom-cards/upcoming-media-card) and all its supported integrations (like Plex Recently Added) to die since UMC is one of my all-time favorite cards.  Hence, I brought them back to life.  Please check out all the [new features](https://github.com/custom-cards/upcoming-media-card#) for UMC.  

This Plex integration recently added support for common library **types:** `photo`, `artist`, `music`, etc); in addition to `show` and `movie`,  You can also specify which libraries from your Plex setup that you want to use:  I.E., `Movies`,  `TV Shows`, `Kids Shows`, etc.  
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/a80a0c12-3c8b-4666-9e23-b4c6a983c9f9)
This all can now be configured from within Home Assistant's GUI (after you install the components in HACS).   These recent features was introduced thanks to @Makhuta !  He pretty much rewrote the entire integration. 

**I am still waiting for all the original repos: UMC, Plex Recently Added , Radarr Upcoming , Sonarr Upcoming integrations to be added back to to HACS.  **Currently, you have to add the repos manually to HACS** (unless you never removed them on your setup)**.  You will see the warnings below in HACS, just click `Ignore`.  This will go away as soon as these reports are officially added back to Home Assistant..  I submitted the respective PR's to HACS 2-3 months ago.  Hopefully, it won't be much longer.

You can click on "SHOW", then select "IGNORE"
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/3c9c58d0-9d36-4cfc-a35c-a16f4905182d)

![image](https://github.com/custom-components/sensor.plex_recently_added/assets/811008/622f02df-9f70-426e-8e1f-03cf66f90978)

**Comment by Makhuta** [comment]
I can confirm that the music part should work without problems, with the photos I am not quite sure I personally don't use it in my setup (but I tried to make temporary library just for photos and it worked) so there may be some bugs.

Here is example of the music instance, it works exactly same as the movie/show:
![image](https://github.com/custom-components/sensor.plex_recently_added/assets/23267923/b6e25889-0b7a-4b20-8e87-5d15f0191e7b)

**Comment by moonbit5** [comment]
Thanks so much for adding this feature. 

<img width="1065" alt="Screenshot 2024-06-01 at 07 35 46" src="https://github.com/custom-components/sensor.plex_recently_added/assets/57290277/ae143926-0d53-42ac-9de0-9186228e353a">
